version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: itiufscar
      RABBITMQ_DEFAULT_PASS: itiufscar

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: itiufscar
      MINIO_ROOT_PASSWORD: itiufscar
    command: server /data --console-address ":9001"

  mqtt:
    image: eclipse-mosquitto:1.6.15-openssl
    ports:
      - "1883:1883"

volumes:
  minio-data:
