version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:1.6.15-openssl
    volumes:
      - ./password.txt:/etc/mosquitto/passwd
      - ./mqtt.conf:/etc/mosquitto/mosquitto.conf
    ports:
      - "1883:1883"
